AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DTH_AWS
  SAM Template for Express backend

Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        FRONTEND_ORIGIN: "http://127.0.0.1:5173,http://localhost:5173"

Resources:
  ExpressBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: handler.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        ProxyRoute:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootRoute:
          Type: Api
          Properties:
            Path: /
            Method: ANY
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - handler.ts

Outputs:
  BackendApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  ExpressBackendFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ExpressBackendFunction.Arn
  ExpressBackendFunctionIamRole:
    Description: Implicit IAM Role ARN
    Value: !GetAtt ExpressBackendFunctionRole.Arn
