AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DTH Leeromgeving - Event-driven API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 128

Resources:
  ExpressBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: handler.lambdaHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: arn:aws:events:us-east-1:883218392606:event-bus/default
      Environment:
        Variables:
          MONGODB_URI: mongodb+srv://BrokeMo:boV4QYrwCcwBZOA1@cluster0.jtprcms.mongodb.net/?appName=Cluster0
          DB_NAME: dth

  UserRegisteredHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: server/
      Handler: userRegisteredHandler.handler
      Events:
        UserRegisteredEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "dth.leeromgeving.user"
              detail-type:
                - "UserRegistered"

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"