name: Send Commit To Discord

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit to Discord
        run: |
          # Short SHA
          SHORT_SHA=${GITHUB_SHA::7}
          REPO_NAME=${GITHUB_REPOSITORY#*/}  # removes 'itmoz/'

          # Random quotes list
          QUOTES=(
            "I’ve been playing piano since I was six or seven and I was lucky enough my first piano teacher thought I was a complete and utter disaster. After a while he just quit."
            "Radiatie? Het heet uitstraling."
            "het is niet een kamerlid die, het is een kamerlid dát! DAT DAT DAT!!! Potdomme."
            "Who is the REAL protagonist of Skyrim? I don't think it's the Dragonborn..."
            "De publisher zei dat als ik de game een jaar eerder of later had geplubished was ik nu miljoenair"
            "Heb niet vaak iets positiefs te melden over het geschrijf van Nederlandse gamejournalisten, maar deze column is raak. Chapeau."
            "Wat een onzin ook. Ik vind het amateuristisch. Stel mensen dat nooit een bedrijf heeft gerund beoordeeld hierover."
            "Ik wil hem echt in het water gooien"
            "Cadeautip 😊 🎅 Voor jongvolwassenen (én volwassenen) die van échte fantasy houden: 'Het verdwenen woud' (14+, 480 pagina's, paperback & ebook)."
            "Ach, een beetje reclame voor mijn eigen boek, dat vergeven jullie me vast. 😉"
            "Val dood."
            "Ik snap sowieso niet wat dit in hemelsnaam met iets als 'metaverse' te maken heeft. Dit is ook geen AI. Ver gezocht om zoiets te koppelen aan het metaverse, beetje gezwets zelfs."
            "MIJN EERSTE BOEK! Ja, hier ben ik ongelooflijk trots op. Onder het pseudoniem Matthew X. Dyer verschijnt in oktober 'Het verdwenen woud'. Mijn eerste fantasyroman, jaren aan gewerkt, vier keer volledig herschreven."
            "Eh, nee, Vincent, absoluut niet. Jij staat bij Playful. Anders zijn we geen vriendjes meer."
            "Kies een taal, en stick with it"
            "Begroting is met één o."
            "Mijn klasgenoten ZIJN ermee eens."
            "Ga naar de kapper."
            "Ben je nou nog steeds niet gestopt met roken."
            "Mo is dood gegaan door het roken"
            "I write books. In Dutch. 😊"
            "This is not vibe coding. This is AI-assisted coding. There is a difference."
            "De gamesindustrie is níet de meest volatile cultuursector in Nederland."
            "Programmer art alert! 😉"
            "Do not go gentle into that good night."
            "Rage, rage against the dying of the light."
            "Ik huil zelden bij een documentaire"
            "Kleine waarschuwing: de laatste ChatGPT-update heeft moeite met Nederlands."
            "Waarom mensen nog steeds nodig zijn..."
            "Ik heb de dapperste zus van Nederland. Met haar team bij het OM de gevaarlijkste criminelen van Nederland vervolgen en er dan bij Nieuwsuur alles over vertellen."
            "The real protagonist is the world"
            "Absoluut fantastisch, dit soort initiatieven!"
            "Unexplored 2 remains the most beautiful game I've ever worked on. It did not bring the (commercial) success we were hoping for, but it is still being updated to this day, so who know... maybe it'll gain steam on Steam one of these days 🙏"
            "Als schrijver is dit hoe je jouw boek het liefste ziet: letterlijk stukgelezen! 🤗"
            "Ik sta zelf geregeld voor een groep HBO-ICT-studenten. Hun Nederlands is vaak slecht, hun Engels meestal nóg slechter. Paternotte spreekt over het gewenste resultaat, maar slaat daarbij twee noodzakelijke stappen over: 1: Herstel eerst het niveau van het Nederlands in basis- en middelbaar onderwijs Leerlingen en studenten hebben momenteel de grootste moeite zinnen te vormen in hun éigen taal, in het Nederlands. Los van de stortvloed aan taalfouten betekenen hun zinnen vaak iets anders dan hetgeen de leerlingen willen communiceren. Wie zich niet goed kan uitdrukken in zijn eigen taal, kan dat al helemáál niet in een vreemde taal. 2: Verbeter het niveau van het Engels dat leraren bezigen In mijn ervaring is het Engels van de meeste docenten vaak te slecht om onderwijs te geven op niveau. Dit geldt voor zowel middelbaar als hoger (beroeps)onderwijs. Voor de uitleg van complexe onderwerpen is een diep begrip van de gekozen taal nodig, inclusief het benodigde vocabulaire. Pas nádat deze twee stappen succesvol zijn afgerond, valt weer te denken aan Engels als voertaal op hogere onderwijsinstellingen."
          )

          # Pick a random quote
          RANDOM_QUOTE=$(printf "%s\n" "${QUOTES[@]}" | shuf -n 1)

          # Send to Discord
          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"author\": {
                \"name\": \"${{ github.actor }}\",
                \"icon_url\": \"https://github.com/${{ github.actor }}.png\"
              },
              \"title\": \"[${REPO_NAME}:${{ github.ref_name }}] 1 new commit\",
              \"url\": \"${{ github.event.head_commit.url }}\",
              \"description\": \"[[\`\`${SHORT_SHA}\`\`]](${{ github.event.head_commit.url }}) ${{ github.event.head_commit.message }}\",
              \"color\": 12733002,
              \"fields\": [
                {
                  \"name\": \"\u200b\",
                  \"value\": \"Matthew X. Quote: *${RANDOM_QUOTE}*\",
                  \"inline\": false
                }
              ]
            }]
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
